### ISSUE TITLE
curly bracket missing

### ISSUE THREAD

**Issue by horus1963** [JayBrown/DNSCrypt-Menu#1]
Dear Jay,

The plugin was giving me a syntax error. I found that a curly bracket is missing in line 1957 of version 1.0.17 as follows:

Line 1957 is:
syslog=$(echo "$syslogline" | awk -F" = " 'print $2}')
Should be:
syslog=$(echo "$syslogline" | awk -F" = " '{print $2}')

Otherwise it works great. Excellent work!

**Comment by JayBrown** [comment]
Thank you! Should be fixed now. The weird thing is that I never received that syntax error.
