### ISSUE TITLE
Can you add a "Restart" option under "DNSCrypt Service" to Restart DNSCrypt-Proxy?

### ISSUE THREAD

**Issue by rr0ss0rr** [JayBrown/DNSCrypt-Menu#3]
J .. I know there are different ways to install, but if folks take your recommendation to install via brew, perhaps you can add a "sudo brew services restart"?

Thanks .. menu is working great.

**Comment by JayBrown** [comment]
It's already included: if you press the ALT key, you can "Force-Restart" the service, which runs the command `sudo brew services restart dnscrypt-proxy` or the non-brew equivalent, depending on how you installed it. (Default without ALT key is just click on "DNSCrypt Service" to start & stop.)

Glad the plugin is working. There will surely be some issues down the line, but for me it's sufficient for the time being. :)
